// <auto-generated />
namespace API_QL_Nha_hang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HC));
        
        string IMigrationMetadata.Id
        {
            get { return "202105260730586_HC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
